# Generated by Django 3.1.7 on 2022-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('star_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=30000)),
                ('star_rating', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Programari',
            new_name='Appointemnt',
        ),
        migrations.RenameField(
            model_name='appointemnt',
            old_name='nume',
            new_name='name',
        ),
    ]
