# Generated by Django 3.1.7 on 2022-01-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220110_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointemnt',
            new_name='Appointment',
        ),
    ]
