# Generated by Django 3.1.7 on 2022-01-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220110_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
