# Generated by Django 3.1.7 on 2022-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_servicii'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicii',
            new_name='Services',
        ),
    ]
